services:
  migrate_reset:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migrator
    # Service khusus untuk reset database (Wipe data + Migrate Schema)
    # Jalankan manual: docker compose run --rm migrate_reset
    container_name: sb_migrate_reset
    command: pnpm prisma migrate reset --force
    env_file:
      - .env
    networks:
      - global_proxy
      - sb_internal
    profiles:
      - manual

  seed:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migrator
    # Service khusus untuk seeding database
    # Jalankan manual: docker compose run --rm seed
    container_name: sb_seed
    # Generate client dulu untuk memastikan schema terbaru ada, baru jalankan seed script
    command: /bin/sh -c "pnpm prisma generate && pnpm tsx prisma/seed.ts"
    env_file:
      - .env
    networks:
      - global_proxy
      - sb_internal
    profiles:
      - manual

  sb_app_new:
    container_name: sb_app_new
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_DEVICE_ID=${WHATSAPP_DEVICE_ID}
      - WHATSAPP_AUTH_USER=${WHATSAPP_AUTH_USER}
      - WHATSAPP_AUTH_PASS=${WHATSAPP_AUTH_PASS}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      # Pusher
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - NEXT_PUBLIC_PUSHER_KEY=${NEXT_PUBLIC_PUSHER_KEY}
      - PUSHER_SECRET=${PUSHER_SECRET}
      - NEXT_PUBLIC_PUSHER_CLUSTER=${NEXT_PUBLIC_PUSHER_CLUSTER}
      - NEXT_PUBLIC_PUSHER_TLS=${NEXT_PUBLIC_PUSHER_TLS}
      - NEXT_PUBLIC_PUSHER_HOST=${NEXT_PUBLIC_PUSHER_HOST}
      - NEXT_PUBLIC_PUSHER_PORT=${NEXT_PUBLIC_PUSHER_PORT}
    expose:
      - "3000"
    networks:
      - global_proxy
      - sb_internal

networks:
  global_proxy:
    external: true
  sb_internal:
    driver: bridge