services:
  sb_app_new:
    container_name: sb_app_new
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_DEVICE_ID=${WHATSAPP_DEVICE_ID}
      - WHATSAPP_AUTH_USER=${WHATSAPP_AUTH_USER}
      - WHATSAPP_AUTH_PASS=${WHATSAPP_AUTH_PASS}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    networks:
      - global_proxy
      - sb_internal

networks:
  global_proxy:
    external: true
  sb_internal:
    driver: bridge